config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :routes
  resources :maintenances
  resources :fuel_tanks
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-custom">
  <a class="navbar-brand" href="/">
    <%= image_tag 'logo' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="<%= current_page?(root_path) ? 'nav-item active' : 'nav-item' %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <li class="nav-item dropdown">
        <%= image_tag "https://s.gravatar.com/avatar/d69d6443f4cb29d65d570a2081396ea2?s=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Veículos", vehicles_path, class: "dropdown-item" %>
          <%= link_to "Rotas", routes_path, class: "dropdown-item" %>
          <%= link_to "Manutenções", maintenances_path, class: "dropdown-item" %>
          <%= link_to "Tanques", fuel_tanks_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>