config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :routes
  resources :maintenances
  resources :fuel_tanks
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fuel_tank.rb
class FuelTank < ApplicationRecord
  include FuelData

  validates :capacity, :amount, :fuel, presence: true
  validates :capacity, numericality: { greater_than: 0 }
  validates :amount, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: :capacity,
    message: "deve estar entre 0 e o valor da capacidade"
  }

  enum fuel: { diesel: 1, alcool: 2, gasolina: 3 }

  def info
    message = "Capacidade: #{capacity} (L) - "
    message += "Quantidade: #{amount} (L) - "
    message += "Combustível: #{fuel}"

    message
  end

  def travel(distance)
    fuel_data = current_fuel_data
    self.amount -= (distance.to_f / fuel_data[:autonomy])

    save!
  end

  # returns an float representing the max autonomy in kms. eg: 400 meaning 400 kms
  def max_autonomy
    fuel_data = current_fuel_data

    (capacity * fuel_data[:autonomy]).to_f
  end

  # returns an float representing the current autonomy in kms. eg: 400 meaning 400 kms
  def current_autonomy
    fuel_data = current_fuel_data

    (self.amount * fuel_data[:autonomy]).to_f
  end

  # returns an hash having the autonomy and price per L considering the fuel type
  def current_fuel_data
    return FuelData::ALCOHOL if fuel.upcase == "ALCOOL"
    return FuelData::GASOLINE if fuel.upcase == "GASOLINA"
    return FuelData::DIESEL if fuel.upcase == "DIESEL"
  end
end

app/controllers/fuel_tanks_controller.rb
class FuelTanksController < ApplicationController
  before_action :set_fuel_tank, only: %i[show edit update destroy]

  # GET /fuel_tanks
  def index
    @fuel_tanks = FuelTank.all
  end

  # GET /fuel_tanks/1
  def show
  end

  # GET /fuel_tanks/new
  def new
    @fuel_tank = FuelTank.new
  end

  # GET /fuel_tanks/1/edit
  def edit
  end

  # POST /fuel_tanks
  def create
    @fuel_tank = FuelTank.new(fuel_tank_params)

    if @fuel_tank.save
      redirect_to @fuel_tank, notice: 'Tanque de combustível criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /fuel_tanks/1
  def update
    if @fuel_tank.update(fuel_tank_params)
      redirect_to @fuel_tank, notice: 'Tanque de combustível atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /fuel_tanks/1
  def destroy
    @fuel_tank.destroy
    redirect_to fuel_tanks_url, notice: 'Tanque de combustível excluído com sucesso.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fuel_tank
    @fuel_tank = FuelTank.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def fuel_tank_params
    params.require(:fuel_tank).permit(:capacity, :amount, :fuel)
  end
end

app/views/fuel_tanks/_form.html.erb
<%= simple_form_for(@fuel_tank) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= f.input :capacity, label: 'Capacidade', required: true, autofocus: true %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= f.input :amount, label: 'Quantidade', required: true %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= f.input :fuel, label: 'Combustível', collection: FuelTank.fuels.keys %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, locals[:button_label], { class: 'btn btn-primary' } %>
  </div>
<% end %>

app/views/fuel_tanks/edit.html.erb
<h1 class="m-3">Editar Tanque de Combustível</h1>

<%= render 'form', fuel_tank: @fuel_tank, locals: {button_label: 'Editar Tanque'} %>

<%= link_to 'Detalhes', @fuel_tank %> |
<%= link_to 'Voltar', fuel_tanks_path %>

app/views/fuel_tanks/index.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Tanques de Combustível</h1>
<%= link_to 'Novo Tanque', new_fuel_tank_path, :class => "btn btn-primary mb-3" %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Capacidade (L)</th>
      <th scope="col">Quantidade (L)</th>
      <th scope="col">Combustível</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @fuel_tanks.each do |fuel_tank| %>
      <tr>
        <td><%= fuel_tank.capacity %></td>
        <td><%= fuel_tank.amount %></td>
        <td><%= fuel_tank.fuel %></td>
        <td>
          <%= link_to fuel_tank, :class => "btn btn-success" do %>
            <span>Detalhes <%= icon('fas', 'gas-pump') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_fuel_tank_path(fuel_tank), :class => "btn btn-info" do %>
            <span>Editar <%= icon('fas', 'edit') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to fuel_tank, :class => "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } do %>
            <span>Excluir <%= icon('fas', 'trash-alt') %></span>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fuel_tanks/new.html.erb
<h1 class="m-3">Novo Tanque de Combustível</h1>

<%= render 'form', fuel_tank: @fuel_tank, locals: { button_label: 'Novo Tanque' } %>

<%= link_to 'Voltar', fuel_tanks_path %>

app/views/fuel_tanks/show.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Detalhes do Tanque de Combustível</h1>
<div class="mb-3">
  <%= link_to 'Editar', edit_fuel_tank_path(@fuel_tank) %> |
  <%= link_to 'Voltar', fuel_tanks_path %>
</div>

<p>
  <strong>Capacidade:</strong>
  <%= @fuel_tank.capacity %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @fuel_tank.amount %>
</p>

<p>
  <strong>Combustível:</strong>
  <%= @fuel_tank.fuel %>
</p>