config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :routes
  resources :maintenances
  resources :fuel_tanks
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :vehicle, optional: true
  validates :date, :size, presence: true
  validates :size, numericality: { greater_than: 0 }

  before_create :check_constraints, if: -> { vehicle }
  before_update :check_constraints, if: -> { vehicle }
  after_create :inform_vehicle, if: -> { vehicle }
  after_update :inform_vehicle, if: -> { vehicle }

  def info
    "Data: #{date} - Tamanho #{size} (Km's)"
  end

  private

  def check_constraints
    vehicle_data = vehicle.next_maintenance_data
    if vehicle_data[:kms_until] < size
      error_mesage = "o veículo precisará entrar em manutenção em #{vehicle_data[:kms_until]} kms"
      errors.add(:size, error_mesage)
      raise ActiveRecord::RecordInvalid
    end

    if vehicle.max_autonomy < size
      errors.add(:size, "a autonomia do veículo é inferior")
      raise ActiveRecord::RecordInvalid
    end

    if vehicle.current_autonomy < size
      errors.add(:size, "o veículo não possui combustível suficiente")
      raise ActiveRecord::RecordInvalid
    end
  end

  def inform_vehicle
    vehicle.accept_route(size)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: %i[show edit update destroy]

  # GET /routes
  def index
    @routes = Route.all
  end

  # GET /routes/1
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route, notice: 'Rota criada com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /routes/1
  def update
    if @route.update(route_params)
      redirect_to @route, notice: 'Rota atualizada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /routes/1
  def destroy
    @route.destroy
    redirect_to routes_url, notice: 'Rota excluída com sucesso.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_route
    @route = Route.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def route_params
    params.require(:route).permit(:date, :size, :vehicle_id)
  end
end

app/views/routes/_form.html.erb
<%= simple_form_for(@route) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row justify-content-center">
      <div class="col-lg-2">
        <%= f.input :date, as: :string, label: "Data", input_html: {class: "datepicker"}, required: true %>
      </div>
      <div class="col-lg-2">
        <%= f.input :size, label: "Tamanho (Km's)" %>
      </div>
      <div class="col-lg-6">
        <%= f.association :vehicle, label: "Veículo", label_method: :info, value_method: :id, required: true %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, locals[:button_label], { class: 'btn btn-primary' } %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1 class="m-3">Editar Rota</h1>

<%= render 'form', route: @route, locals: { button_label: 'Editar Rota' } %>

<%= link_to 'Detalhes', @route %> |
<%= link_to 'Voltar', routes_path %>

app/views/routes/index.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Rotas</h1>
<%= link_to 'Nova Rota', new_route_path, :class => "btn btn-primary mb-3" %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Data</th>
      <th>Tamanho (Km's)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= format_date(route.date) %></td>
        <td><%= route.size %></td>
        <td>
          <%= link_to route, :class => "btn btn-success" do %>
            <span>Detalhes <%= icon('fas', 'route') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_route_path(route), :class => "btn btn-info" do %>
            <span>Editar <%= icon('fas', 'edit') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to route, :class => "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } do %>
            <span>Excluir <%= icon('fas', 'trash-alt') %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/routes/new.html.erb
<h1 class="m-3">Nova Rota</h1>

<%= render 'form', route: @route, locals: { button_label: 'Nova Rota' } %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Detalhes da Rota</h1>
<div class="mb-3">
  <%= link_to 'Editar', edit_route_path(@route) %> |
  <%= link_to 'Voltar', routes_path %>
</div>

<p>
  <strong>Data:</strong>
  <%= format_date(@route.date) %>
</p>

<p>
  <strong>Tamanho:</strong>
  <%= @route.size.to_f %> (Km's)
</p>

<p>
  <strong>Veículo:</strong>
  <%= link_to @route.vehicle.info, @route.vehicle %>
</p>