config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :routes
  resources :maintenances
  resources :fuel_tanks
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  include MaintenanceCategories

  belongs_to :fuel_tank
  has_many :routes, dependent: :destroy
  has_many :maintenances, dependent: :destroy

  validates :plate, :distance_traveled, :tipo, presence: true
  validates :fuel_cost, numericality: { greater_than_or_equal_to: 0 }
  validates :distance_traveled, numericality: { greater_than_or_equal_to: 0 }

  enum tipo: { "Caminhão": 1, "Van": 2, "Furgão": 3, "Carro": 4 }

  def info
    "#{tipo} com placa #{plate}"
  end

  # returns an float representing the max autonomy in kms. eg: 400 meaning 400 kms
  def max_autonomy
    fuel_tank.max_autonomy
  end

  # returns an float representing the current autonomy in kms. eg: 400 meaning 400 kms
  def current_autonomy
    fuel_tank.current_autonomy
  end

  # returns an hash having the autonomy and price per L considering the fuel type
  def current_fuel_data
    fuel_tank.current_fuel_data
  end

  # returns an hash having the following data related to the next maintenance:
  # kms to it, maintenance messages
  def next_maintenance_data
    periodic = calc_distance(:periodic)
    parts_change = calc_distance(:parts_change)

    if periodic < parts_change
      return { kms_until: periodic, message: MaintenanceCategories::MESSAGE[:periodic], amount: 1 }
    end
    if parts_change < periodic
      return { kms_until: parts_change, message: MaintenanceCategories::MESSAGE[:parts_change], amount: 1 }
    end

    return { kms_until: periodic,
             message: "#{MaintenanceCategories::MESSAGE[:periodic]} - #{MaintenanceCategories::MESSAGE[:parts_change]}",
             amount: 2 }
  end

  def maintenance_category
    return MaintenanceCategories::SIZE_250 if fuel_tank.capacity.to_f >= 250
    return MaintenanceCategories::SIZE_80 if fuel_tank.capacity.to_f >= 80
    return MaintenanceCategories::SIZE_60 if fuel_tank.capacity.to_f >= 60

    return MaintenanceCategories::SIZE_50
  end

  def accept_route(route_size)
    verify_maintenance(route_size)
    self.distance_traveled += route_size
    fuel_tank.travel(route_size)
    fuel_data = current_fuel_data
    self.fuel_cost += (route_size.to_f / fuel_data[:autonomy]) * fuel_data[:price]
    save!
  end

  def maintenances_cost
    cost = 0
    maintenances.each do |maintenance|
      cost += maintenance.price
    end
    cost
  end

  private

  # auxiliary method to calculate the distance depending on the symbol passed
  def calc_distance(type)
    category = maintenance_category

    category[type] - (distance_traveled % category[type])
  end

  def verify_maintenance(additional_distance)
    if additional_distance >= next_maintenance_data[:kms_until] # should have a maintenance
      next_maintenance_data[:amount].times do
        add_maintenance
      end
    end
  end

  def add_maintenance
    Maintenance.create(date: Date.tomorrow, vehicle_id: id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]

  # GET /vehicles
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle, notice: 'Veículo criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /vehicles/1
  def update
    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Veículo atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /vehicles/1
  def destroy
    @vehicle.destroy
    redirect_to vehicles_url, notice: 'Veículo excluído com sucesso.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def vehicle_params
    params.require(:vehicle).permit(:plate, :tipo, :fuel_tank_id, :distance_traveled, route_ids: [], maintenance_ids: [])
  end
end

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-lg-6">
        <%= f.input :plate, label: 'Placa', required: true, autofocus: true %>
      </div>
      <div class="col-lg-6">
        <%= f.input :tipo, label: 'Tipo', collection: Vehicle.tipos.keys %>
      </div>
      <div class="col-lg-7">
        <%= f.association :fuel_tank, label: "Tanque de Combustível", label_method: :info, value_method: :id, required: true %>
      </div>
      <div class="col-lg-2">
        <%= f.input :fuel_cost, label: 'Custo Atual', required: true %>
      </div>
      <div class="col-lg-3">
        <%= f.input :distance_traveled, label: "Distância Percorrida (Km's)", required: true %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, locals[:button_label], { class: 'btn btn-primary' } %>
  </div>
<% end %>

app/views/vehicles/_form_edit.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= f.association :fuel_tank, label: "Tanque de Combustível", label_method: :info, value_method: :id, required: true %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= f.input :distance_traveled, label: "Distância Percorrida (Km's)", required: true %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, locals[:button_label], { class: 'btn btn-primary' } %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1 class="m-3">Editar Veículo</h1>

<%= render 'form_edit', vehicle: @vehicle, locals: { button_label: 'Editar Veículo' } %>

<%= link_to 'Detalhes', @vehicle %> |
<%= link_to 'Voltar', vehicles_path %>

app/views/vehicles/index.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Veículos</h1>
<%= link_to 'Novo Veículo', new_vehicle_path, class: "btn btn-primary mb-3" %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Veículo</th>
      <th scope="col">Custo Total</th>
      <th scope="col">Distância Percorrida (Km's)</th>
      <th scope="col">Autonomia Atual (Km's)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.info %></td>
        <td><%= price_mask_real(vehicle.fuel_cost + vehicle.maintenances_cost) %></td>
        <td><%= vehicle.distance_traveled %></td>
        <td><%= vehicle.current_autonomy %></td>
        <td>
          <%= link_to vehicle, :class => "btn btn-success" do %>
            <span>Detalhes <%= icon('fas', 'car') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_vehicle_path(vehicle), :class => "btn btn-info" do %>
            <span>Tanque <%= icon('fas', 'gas-pump') %></span>
          <% end %>
        </td>
        <td>
          <%= link_to vehicle, :class => "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza?' } do %>
            <span>Excluir <%= icon('fas', 'trash-alt') %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/new.html.erb
<h1 class="m-3">Novo Veículo</h1>

<%= render 'form', vehicle: @vehicle, locals: { button_label: 'Novo Veículo' } %>

<%= link_to 'Voltar', vehicles_path %>

app/views/vehicles/show.html.erb
<% if notice %>
  <div id="notice" class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <%= icon('fas', 'times') %>
    </a>
  </div>
<% end %>

<h1 class="m-3">Detalhes do Veículo</h1>
<div class="mb-3">
  <%= link_to 'Editar', edit_vehicle_path(@vehicle) %> |
  <%= link_to 'Voltar', vehicles_path %>
</div>

<p>
  <strong>Placa:</strong>
  <%= @vehicle.plate %>
</p>

<p>
  <strong>Tanque de Combustível:</strong>
  <%= FuelTank.find(@vehicle.fuel_tank_id).info %>
</p>

<p>
  <strong>Autonomia Atual:</strong>
  <%= @vehicle.current_autonomy %> (Km's)
</p>

<p>
  <strong>Custos com combustível:</strong>
  <%= price_mask_real(@vehicle.fuel_cost) %>
</p>

<p>
  <strong>Custos com manutenções:</strong>
  <%= price_mask_real(@vehicle.maintenances_cost) %>
</p>

<p>
  <strong>Distância Percorrida:</strong>
  <%= @vehicle.distance_traveled.to_f %> (Km's)
</p>

<p>
  <strong>Manutenções:</strong>
  <% @vehicle.maintenances.each do |maintenance| %>
    <p><%= link_to maintenance.info, maintenance %></p>
  <% end %>
</p>

<p>
  <strong>Rotas:</strong>
  <% @vehicle.routes.each do |route| %>
    <p><%= link_to route.info, route %></p>
  <% end %>
</p>